; AutoSizer.ini
[__WindowSizer__]
SoundMode=Wav
BeepFreq=400
BeepDur=40
WavPath=C:\Windows\Media\Speech Misrecognition.wav

[py - Notepad++]
Compare=Title
Class=Notepad++
Title=.py - Notepad++
TitleMatch=Contains
W=1150
H=800
X=100
Y=70

[bat - Notepad++]
Compare=Title
Class=Notepad++
Title=*alias.bat - Notepad++
TitleMatch=Contains
W=1168
H=800
X=100
Y=80
[Generic Notepad++]
Compare=Class
Class=Notepad++
Title=ERROR
TitleMatch=Exact
W=1720
H=800
X=100
Y=70
