; MiniTray.ini

[__MiniTray__]
BeepDur=40
BeepFreq=400
SoundMode=None
WavPath=C:\Windows\Media\Speech Misrecognition.wav
AutoApply=1
ConfirmCloseAll=1
HideIconWhenEmpty=1
Speak=1
[explorer]
Compare=Class
Class=CabinetWClass
Title=v2.0 - File Explorer
TitleMatch=exact
W=1600
H=1100
X=520
Y=160
Bounds=work
HideOnMinimize=0
Enabled=1
